### PR TITLE
Enhance Concurrency and Cancellation Handling in Job Execution

### PR DESCRIPTION
**Pull request by falvarez1**
### Description:
This Pull Request introduces significant enhancements to how concurrency and cancellation are managed within job executions. Key changes include:

- **Asynchronous Execution Enhancements**: All job runs are now fully asynchronous, ensuring that operations are non-blocking and responsive throughout their execution paths.
- **Improved Cancellation Support**: Enhancements to cancellation token usage allow for more responsive cancellation of ongoing jobs. Cancellation checks are integrated more deeply into the job execution logic, allowing for quicker termination of jobs in response to cancellation requests.
- **Concurrency Control with Priority Queue**: Implemented a priority queue-based concurrency control mechanism. This allows multiple job instances to run in parallel while respecting priority constraints.

These changes aim to make the job execution process more efficient, responsive, and reliable, particularly under high load and in complex scheduling scenarios.

Future work, the concurrency control responsibilities still need to be moved into the JobExecutor , this shift will centralize how parallel executions are managed, simplifying maintenance and extending capabilities.

### CODE REVIEW

**Comment by falvarez1** [comment]
Since #21 piggybacks on this one I suppose this one is unnecessary. I probably should have worked on the same branch but wasn't sure about your contributions preferences.

**Comment by falvarez1** [comment]
One thing to note, the Tests are broken at the moment. I didn't spend any time fixing them because I just wanted to have you review the design changes first.

**Comment by linkdotnet** [comment]
That is fine - they can be fixed afterward.

**Comment by falvarez1** [comment]
Closing this PR as it is superceded by #21.

**Pull request closed without merging**
